version: '3.6'
services:
    postgres:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: hasura
            POSTGRES_PASSWORD: hasura_password
            POSTGRES_DB: hasura_db
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data

    graphql-engine:
        image: hasura/graphql-engine:v2.34.0.ubuntu.arm64
        depends_on:
            - postgres
        restart: always
        ports:
            - '8080:8080'
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura_password@postgres:5432/hasura_db
            HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            HASURA_GRAPHQL_ADMIN_SECRET: my_admin_secret_key
            HASURA_GRAPHQL_ENABLE_ALLOWLIST: 'true'
            ADMIN_SECRET: my_admin_secret_key
            HASURA_GRAPHQL_JWT_SECRET: |
                {
                 "audience": "shatax-c10f9",
                 "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com",
                 "claims_map":{
                    "x-hasura-allowed-roles": ["user"],
                    "x-hasura-default-role": "user",
                    "x-hasura-user-id": { "path": "$.sub" }
                    },
                 "type": "RS256",
                 "issuer": "https://securetoken.google.com/shatax-c10f9"
                }
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest

volumes:
    postgres-data:
